/**
 * HTBB build — combines the per-module files into one CSS and one JS bundle.
 *
 *   node build.js
 *
 * Edit the files in css/ and js/ as usual, then run this and commit dist/.
 * Each JS module is wrapped in its own try/catch so an error in one module
 * can't stop the modules after it from running.
 */
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const DIST = path.join(ROOT, 'dist');

// Order matches the Squarespace header injection. Videos is loaded on its own page, not here.
const CSS = [
  'css/htbb-new.css',
  'css/calendar.css',
  'css/htbb-menu.css',
  'css/htbb-faqs.css',
  'css/htbb-cast-creative.css',
  'css/htbb-creative.css',
];

const JS = [
  'js/htbb-quotes.js',
  'js/calendar.js',
  'js/htbb-menu.js',
  'js/htbb-faqs.js',
  'js/htbb-cast-creative.js',
  'js/htbb-creative.js',
  'js/htbb-lens.js'
];

const read = file => fs.readFileSync(path.join(ROOT, file), 'utf8').trimEnd();

const banner = `/* HTBB bundle — generated by build.js on ${new Date().toISOString()}. Do not edit; edit the source files instead. */\n`;

const css = banner + CSS.map(file =>
  `\n/* ==================== ${file} ==================== */\n\n${read(file)}\n`
).join('');

const js = banner + JS.map(file =>
  `\n/* ==================== ${file} ==================== */\n` +
  `try {\n${read(file)}\n} catch (error) {\n  console.error('[HTBB] ${file} failed:', error);\n}\n`
).join('');

// Fail the build on a JS syntax error rather than shipping a broken bundle.
new Function(js);

fs.mkdirSync(DIST, { recursive: true });
fs.writeFileSync(path.join(DIST, 'htbb.css'), css);
fs.writeFileSync(path.join(DIST, 'htbb.js'), js);

console.log(`dist/htbb.css  ${CSS.length} files, ${(css.length / 1024).toFixed(1)} KB`);
console.log(`dist/htbb.js   ${JS.length} files, ${(js.length / 1024).toFixed(1)} KB`);
